CREATE TABLE IF NOT EXISTS users(
 id UUID PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(255) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 provider VARCHAR(40) NOT NULL DEFAULT 'local',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique
 ON users (lower(email));
